//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management_System.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLACTION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLACTION()
        {
            this.TBLPUNISHMENT = new HashSet<TBLPUNISHMENT>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Book { get; set; }
        public Nullable<int> Member { get; set; }
        public Nullable<int> Employee { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public Nullable<System.DateTime> GetirdigiTarih { get; set; }
        public Nullable<bool> Durum2 { get; set; }
    
        public virtual TBLBOOK TBLBOOK { get; set; }
        public virtual TBLEMPLOYEE TBLEMPLOYEE { get; set; }
        public virtual TBLMEMBERS TBLMEMBERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLPUNISHMENT> TBLPUNISHMENT { get; set; }
    }
}
