//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management_System.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLBOOK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLBOOK()
        {
            this.TBLACTION = new HashSet<TBLACTION>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<byte> Category { get; set; }
        public Nullable<int> Author { get; set; }
        public string EditionYear { get; set; }
        public string PublishingHouse { get; set; }
        public string Page { get; set; }
        public Nullable<bool> Status { get; set; }
        public string BookImages { get; set; }
        public string BookDetails { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLACTION> TBLACTION { get; set; }
        public virtual TBLAUTHOR TBLAUTHOR { get; set; }
        public virtual TBLCATEGORY TBLCATEGORY { get; set; }
    }
}
