//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management_System.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLPUNISHMENT
    {
        public int ID { get; set; }
        public Nullable<int> Member { get; set; }
        public Nullable<int> Action { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> Money { get; set; }
    
        public virtual TBLACTION TBLACTION { get; set; }
        public virtual TBLMEMBERS TBLMEMBERS { get; set; }
    }
}
